name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Vite requires Node >=20.19.0; use a compatible Node 20.x release
          node-version: '20.19.0'
          # Do not use the npm cache here. Restoring cached platform-specific
          # native artifacts (from macOS/dev machine) can cause Rollup to try
          # to load the wrong native binary on the Linux runner.
          # cache: 'npm'

      - name: Clean and install dependencies (force fresh install)
        run: |
          echo "Runner platform: $(uname -a)"
          node -v || true
          npm -v || true
          # Ensure npm cache is clean to avoid stale/native artifacts
          npm cache clean --force || true

          # Remove any potentially platform-specific lockfile/node_modules
          rm -rf node_modules package-lock.json

          # Perform a fresh install so optional native packages for the
          # runner platform are fetched correctly.
          npm install

          # Quick check: list rollup platform packages (for debugging)
          ls -la node_modules/@rollup || true

      - name: Show build-time env and node info
        run: |
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-<not set>}"
          echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-<not set>}"
          node -v
          npm -v

      - name: Build
        env:
          # keep compatibility secrets
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          REACT_APP_ADMIN_PASSWORD: ${{ secrets.REACT_APP_ADMIN_PASSWORD }}
          # expose Vite-prefixed env vars for use in import.meta.env
          VITE_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          VITE_ADMIN_PASSWORD: ${{ secrets.REACT_APP_ADMIN_PASSWORD }}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
